parameters:
    application.name: PHPCI
    application.version: 1.7-dev
    config_file: PHPCI/config.yml
    storage.factory: b8\Store\Factory

services:
    storage.user:
        class:   PHPCI\Store\UserStore
        factory: [%storage.factory%, getStore]
        arguments:
            - User
    storage.project:
        class:   PHPCI\Store\ProjectStore
        factory: [%storage.factory%, getStore]
        arguments:
            - Project
    storage.build:
        class:   PHPCI\Store\BuildStore
        factory: [%storage.factory%, getStore]
        arguments:
            - Build
    storage.build_meta:
        class:   PHPCI\Store\BuildMetaStore
        factory: [%storage.factory%, getStore]
        arguments:
            - BuildMeta
    http.request:
        class:      b8\Http\Request
        arguments:  []
    http.response:
        class:      b8\Http\Response
        arguments:  []
    http_client.github:
        class:      b8\HttpClient
        arguments:
          - https://api.github.com
    config:
        class:      PHPCI\Config
        arguments:  [%config_file%]
    application:
        class:      PHPCI\Application
        arguments:  [@config, @http.request, @http.response, @storage.user, @storage.project]
    service.build:
        class:      PHPCI\Service\BuildService
        arguments:  [@storage.build]
    service.user:
        class:      PHPCI\Service\UserService
        arguments:  [@storage.user]
    process_control:
        factory: [PHPCI\ProcessControl\Factory, getInstance]
    console.application:
        class:      Symfony\Component\Console\Application
        arguments:
          - %application.name%
          - %application.version%
        calls:
          - [add, ['@console.command.run']]
          - [add, ['@console.command.rebuild']]
          - [add, ['@console.command.install']]
          - [add, ['@console.command.update']]
          - [add, ['@console.command.generate']]
          - [add, ['@console.command.daemon']]
          - [add, ['@console.command.poll']]
          - [add, ['@console.command.create_admin']]
          - [add, ['@console.command.create_build']]
    console.logger:
        class:      Monolog\Logger
        arguments:
          - cli
    console.command.run:
        class:      PHPCI\Command\RunCommand
        arguments:
          - @console.logger
    console.command.rebuild:
        class:      PHPCI\Command\RebuildCommand
        arguments:
          - @console.logger
    console.command.update:
        class:      PHPCI\Command\UpdateCommand
        arguments:
          - @console.logger
          - @config
    console.command.daemon:
        class:      PHPCI\Command\DaemonCommand
        arguments:
          - @console.logger
          - @process_control
    console.command.poll:
        class:      PHPCI\Command\PollCommand
        arguments:
          - @config
          - @console.logger
          - @storage.build
          - @storage.project
          - @http_client.github
    console.command.create_admin:
        class:      PHPCI\Command\CreateAdminCommand
        arguments:
          - @service.user
    console.command.create_build:
        class:      PHPCI\Command\CreateBuildCommand
        arguments:
          - @storage.project
          - @service.build
    console.command.install:
        class:      PHPCI\Command\InstallCommand
    console.command.generate:
        class:      PHPCI\Command\GenerateCommand
